@api=http://localhost:4000

GET {{api}}/users

###
GET {{api}}/auth/signin

###create users
POST {{api}}/auth/signup
Content-Type: application/json

{
    "username":"ernest",
    "email":"ermesto@gmail.com",
    "password":"user"
}

###
POST {{api}}/auth/signin
Content-Type: application/json

{
    
    "email":"ermesto@gmail.com",
    "password":"userd"
}

